Test

In [24]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df_1 = pd.read_excel('/Users/hendrikalbrecht/Dokumente/Z_Übungen/Mavenanalytics/Manufacturing Downtime/Manufacturing_Line_Productivity.xlsx', sheet_name='Line productivity')

In [4]:
df_2 = pd.read_excel('/Users/hendrikalbrecht/Dokumente/Z_Übungen/Mavenanalytics/Manufacturing Downtime/Manufacturing_Line_Productivity.xlsx', sheet_name='Products')
df_3 = pd.read_excel('/Users/hendrikalbrecht/Dokumente/Z_Übungen/Mavenanalytics/Manufacturing Downtime/Manufacturing_Line_Productivity.xlsx', sheet_name='Downtime factors')
df_4 = pd.read_excel('/Users/hendrikalbrecht/Dokumente/Z_Übungen/Mavenanalytics/Manufacturing Downtime/Manufacturing_Line_Productivity.xlsx', sheet_name='Line downtime')

In [30]:
df_1.head()

        Date Product   Batch Operator Start Time  End Time  Total_Downtime
0 2024-08-29  OR-600  422111      Mac   11:50:00  14:05:00            75.0
1 2024-08-29  LE-600  422112      Mac   14:05:00  15:45:00            40.0
2 2024-08-29  LE-600  422113      Mac   15:45:00  17:35:00            50.0
3 2024-08-29  LE-600  422114      Mac   17:35:00  19:15:00            40.0
4 2024-08-29  LE-600  422115  Charlie   19:15:00  20:39:00            24.0

In [29]:
df_1.info()

<class 'pandas.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            38 non-null     datetime64[us]
 1   Product         38 non-null     str
 2   Batch           38 non-null     int64
 3   Operator        38 non-null     str
 4   Start Time      38 non-null     object
 5   End Time        38 non-null     object
 6   Total_Downtime  38 non-null     float64
dtypes: datetime64[us](1), float64(1), int64(1), object(2), str(2)
memory usage: 2.2+ KB

In [31]:
df_1['Operator']

0         Mac
1         Mac
2         Mac
3         Mac
4     Charlie
5     Charlie
6     Charlie
7         Dee
8         Dee
9         Dee
10     Dennis
11     Dennis
12     Dennis
13     Dennis
14    Charlie
15    Charlie
16    Charlie
17    Charlie
18    Charlie
19        Dee
20        Dee
21        Dee
22        Dee
23        Mac
24        Mac
25        Mac
26        Dee
27        Dee
28        Dee
29        Dee
30     Dennis
31     Dennis
32     Dennis
33     Dennis
34    Charlie
35    Charlie
36    Charlie
37        Mac
Name: Operator, dtype: str

In [6]:
df_2.head()

  Product      Flavor    Size  Min batch time
0  OR-600      Orange  600 ml              60
1  LE-600  Lemon lime  600 ml              60
2  CO-600        Cola  600 ml              60
3  DC-600   Diet Cola  600 ml              60
4  RB-600   Root Beer  600 ml              60

In [13]:
df_2.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Product         6 non-null      str
 1   Flavor          6 non-null      str
 2   Size            6 non-null      str
 3   Min batch time  6 non-null      int64
dtypes: int64(1), str(3)
memory usage: 324.0 bytes

In [7]:
df_3.head()

   Factor         Description Operator Error
0       1      Emergency stop             No
1       2        Batch change            Yes
2       3      Labeling error             No
3       4  Inventory shortage             No
4       5       Product spill            Yes

In [12]:
df_3.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Factor          12 non-null     int64
 1   Description     12 non-null     str
 2   Operator Error  12 non-null     str
dtypes: int64(1), str(2)
memory usage: 420.0 bytes

In [16]:
df_4.head()

,Unnamed: 0,Downtime factor,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,Batch,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0
1,422111,NaN,60.0,NaN,NaN,NaN,NaN,15.0,NaN,NaN,NaN,NaN,NaN
2,422112,NaN,20.0,NaN,NaN,NaN,NaN,NaN,20.0,NaN,NaN,NaN,NaN
3,422113,NaN,50.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,422114,NaN,NaN,NaN,25.0,NaN,15.0,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
# 1. Erste Zeile aus df_4 als neue Spaltennamen setzen
df_4_clean = df_4.copy()

df_4_clean.columns = df_4_clean.iloc[0]
df_4_clean = df_4_clean.iloc[1:].reset_index(drop=True)

# 2. Faktor-Mapping aus df_3 erstellen
factor_map = dict(zip(df_3["Factor"], df_3["Description"]))

# 3. Spaltennamen vorbereiten und umbenennen
new_columns = []

for col in df_4_clean.columns:
    # Batch-Spalte behalten
    if col == "Batch":
        new_columns.append("Batch")
    else:
        # aus 1.0 -> 1 machen
        factor_number = int(float(col))
        new_columns.append(factor_map[factor_number])

df_4_clean.columns = new_columns

# 4. Werte numerisch machen, außer Batch
for col in df_4_clean.columns:
    if col != "Batch":
        df_4_clean[col] = pd.to_numeric(df_4_clean[col], errors="coerce")

df_4_clean.head()

,Batch,Emergency stop,Batch change,Labeling error,Inventory shortage,Product spill,Machine adjustment,Machine failure,Batch coding error,Conveyor belt jam,Calibration error,Label switch,Other
0,422111,NaN,60.0,NaN,NaN,NaN,NaN,15.0,NaN,NaN,NaN,NaN,NaN
1,422112,NaN,20.0,NaN,NaN,NaN,NaN,NaN,20.0,NaN,NaN,NaN,NaN
2,422113,NaN,50.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,422114,NaN,NaN,NaN,25.0,NaN,15.0,NaN,NaN,NaN,NaN,NaN,NaN
4,422115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.0,NaN,NaN

In [18]:
df_4_clean.isna().sum()

Batch                  0
Emergency stop        38
Batch change          33
Labeling error        36
Inventory shortage    29
Product spill         35
Machine adjustment    26
Machine failure       27
Batch coding error    32
Conveyor belt jam     37
Calibration error     35
Label switch          35
Other                 32
dtype: int64

In [21]:
# NaN Werte mit '0' füllen

df_4_clean = df_4_clean.fillna(0)
df_4_clean

,Batch,Emergency stop,Batch change,Labeling error,Inventory shortage,Product spill,Machine adjustment,Machine failure,Batch coding error,Conveyor belt jam,Calibration error,Label switch,Other
0,422111,0.0,60.0,0.0,0.0,0.0,0.0,15.0,0.0,0.0,0.0,0.0,0.0
1,422112,0.0,20.0,0.0,0.0,0.0,0.0,0.0,20.0,0.0,0.0,0.0,0.0
2,422113,0.0,50.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,422114,0.0,0.0,0.0,25.0,0.0,15.0,0.0,0.0,0.0,0.0,0.0,0.0
4,422115,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,0.0
5,422116,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,422117,0.0,10.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0
7,422118,0.0,0.0,0.0,0.0,0.0,14.0,16.0,0.0,0.0,0.0,10.0,20.0
8,422119,0.0,0.0,0.0,25.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,422120,0.0,0.0,0.0,20.0,15.0,0.0,0.0,0.0,17.0,0.0,0.0,0.0
10,422121,0.0,0.0,0.0,0.0,0.0,0.0,15.0,0.0,0.0,0.0,0.0,0.0
11,422122,0.0,0.0,0.0,0.0,0.0,0.0,25.0,0.0,0.0,0.0,0.0,0.0
12,422123,0.0,0.0,0.0,43.0,0.0,0.0,30.0,0.0,0.0,0.0,0.0,0.0
13,422124,0.0,0.0,0.0,0.0,20.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0
14,422125,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,10.0
15,422126,0.0,0.0,0.0,0.0,0.0,0.0,0.0,44.0,0.0,0.0,0.0,0.0
16,422127,0.0,0.0,0.0,0.0,0.0,23.0,0.0,0.0,0.0,0.0,0.0,0.0
17,422128,0.0,0.0,0.0,0.0,22.0,0.0,30.0,0.0,0.0,0.0,0.0,0.0
18,422129,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15.0
19,422130,0.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,422131,0.0,0.0,0.0,20.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0
21,422132,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,422133,0.0,0.0,0.0,0.0,0.0,0.0,20.0,0.0,0.0,0.0,0.0,0.0
23,422134,0.0,0.0,0.0,0.0,0.0,0.0,30.0,20.0,0.0,0.0,0.0,0.0
24,422135,0.0,0.0,0.0,30.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15.0
25,422136,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,422137,0.0,0.0,0.0,0.0,0.0,0.0,0.0,30.0,0.0,15.0,0.0,0.0
27,422138,0.0,0.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,422139,0.0,0.0,0.0,20.0,0.0,15.0,0.0,0.0,0.0,0.0,0.0,0.0
29,422140,0.0,0.0,0.0,0.0,0.0,50.0,0.0,0.0,0.0,0.0,13.0,0.0
30,422141,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0
31,422142,0.0,0.0,0.0,0.0,0.0,30.0,0.0,0.0,0.0,0.0,0.0,0.0
32,422143,0.0,0.0,0.0,0.0,0.0,40.0,18.0,0.0,0.0,0.0,0.0,0.0
33,422144,0.0,0.0,0.0,0.0,0.0,30.0,0.0,24.0,0.0,0.0,0.0,0.0
34,422145,0.0,0.0,22.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35,422146,0.0,0.0,0.0,0.0,0.0,30.0,25.0,0.0,0.0,0.0,0.0,7.0
36,422147,0.0,0.0,0.0,17.0,0.0,60.0,30.0,0.0,0.0,0.0,0.0,0.0
37,422148,0.0,0.0,0.0,25.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0

In [22]:
df_4_clean.isna().sum()

Batch                 0
Emergency stop        0
Batch change          0
Labeling error        0
Inventory shortage    0
Product spill         0
Machine adjustment    0
Machine failure       0
Batch coding error    0
Conveyor belt jam     0
Calibration error     0
Label switch          0
Other                 0
dtype: int64

In [23]:
# Berechnen total downtime per batch

df_4_clean["Total_Downtime"] = df_4_clean.drop(columns="Batch").sum(axis=1)

df_4_clean.head()

,Batch,Emergency stop,Batch change,Labeling error,Inventory shortage,Product spill,Machine adjustment,Machine failure,Batch coding error,Conveyor belt jam,Calibration error,Label switch,Other,Total_Downtime
0,422111,0.0,60.0,0.0,0.0,0.0,0.0,15.0,0.0,0.0,0.0,0.0,0.0,75.0
1,422112,0.0,20.0,0.0,0.0,0.0,0.0,0.0,20.0,0.0,0.0,0.0,0.0,40.0
2,422113,0.0,50.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,50.0
3,422114,0.0,0.0,0.0,25.0,0.0,15.0,0.0,0.0,0.0,0.0,0.0,0.0,40.0
4,422115,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,0.0,24.0

In [25]:
df_4_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Batch               38 non-null     object
 1   Emergency stop      38 non-null     float64
 2   Batch change        38 non-null     float64
 3   Labeling error      38 non-null     float64
 4   Inventory shortage  38 non-null     float64
 5   Product spill       38 non-null     float64
 6   Machine adjustment  38 non-null     float64
 7   Machine failure     38 non-null     float64
 8   Batch coding error  38 non-null     float64
 9   Conveyor belt jam   38 non-null     float64
 10  Calibration error   38 non-null     float64
 11  Label switch        38 non-null     float64
 12  Other               38 non-null     float64
 13  Total_Downtime      38 non-null     float64
dtypes: float64(13), object(1)
memory usage: 4.3+ KB

Letzte Spalte von df_4_clean zu df_1 addieren/kopieren

In [26]:
df_1['Total_Downtime'] = df_4_clean['Total_Downtime']

In [27]:
df_1.columns

Index(['Date', 'Product', 'Batch', 'Operator', 'Start Time', 'End Time',
       'Total_Downtime'],
      dtype='str')

In [28]:
df_1.head()

        Date Product   Batch Operator Start Time  End Time  Total_Downtime
0 2024-08-29  OR-600  422111      Mac   11:50:00  14:05:00            75.0
1 2024-08-29  LE-600  422112      Mac   14:05:00  15:45:00            40.0
2 2024-08-29  LE-600  422113      Mac   15:45:00  17:35:00            50.0
3 2024-08-29  LE-600  422114      Mac   17:35:00  19:15:00            40.0
4 2024-08-29  LE-600  422115  Charlie   19:15:00  20:39:00            24.0

#

1. Frage Line efficiency Groupby Product
3. Frage Leading factors -> df_4_clean spalten addieren, dann absteigend sortieren (grösstes zuerst)
2. Frage operators underperforming (nach operators gruppieren (mac, charlie), avg downtime, vergleichen mit avg., dann gucken wer unter und wer über avg. liegt
4. Frage Do operators struggle with particular operator error | operator error J/N (df_3) | df_4 zwei neue spalten J oder N, füllen mit der jeweiligen downtime | zuordnen wieviel zeit operator downtime bzw. maschinelle downtime | df_1 breakdown 75 minuten total downtime (anteil maschinell, anteil human) | per operator gruppieren (mac 100 minuten human, 10 minuten maschinell)
5. Natalia macht Frage 1 + 3, Hendrik macht 2 + 4

In [ ]:
"""
Question #2
Are any operators underperforming?
Possible KPIs
 - average batch time by operator
 - average batchtime overall
 - productivity by operator
 - defect/error rate
"""

In [ ]:
"""
Question #4
Do any operators struggle with a particular operator error?
Possible KPIs
 - which error with which operator
 - how much time per operator
"""